import "./globals.css";
import "./custom.css";
import './indexedDB.js';
import "../styles.css";

export const metadata = {
  title: "Page D'accueil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      {children}
      </body>
    </html>
  );
}
